### ISSUE TITLE
InternationalOptions needs model to attach to items

### ISSUE THREAD

**Issue by jzika** [natecox/pyshipstation#2]

**Comment by natecox** [comment]
@jzika I've added a feature branch for this (`feature/add-international-options`, referenced in the commit above). Can you pull this down and give it a try for me?

**Comment by natecox** [comment]
@jzika Any feedback on this?

**Comment by natecox** [comment]
@jzika I believe that this issue is resolved. `ShipStationOrder` now accepts a `ShipStationInternationalOptions` which in turn accepts a list of `ShipStationCustomsItem`.

I got a developer account from ShipStation and was able to test this successfully, so I'm going to close this issue out and push a new release to PyPI. Please let me know if I have any oversights here, or if any other issues come up.
